site_name: Embedded Systems
pages:
  - Introduction: index.md
  - Operating Systems: operating_systems.md
  - Virtual Machine: virtual_machine.md
  - About: about.md
theme: readthedocs
markdown_extensions:
    - smarty
    - admonition
    - mdx_figures
extra_css:
    - css/extra.css