site_name: Embedded Systems
pages:
  - Introduction: index.md
  - Virtual Machine: virtual_machine.md
  - Linux Basics: linux_basics.md
  - Rpi Operating System: rpi_operating_system.md
  - GIT versioning: git_versioning.md
  - Compiling and Makefiles: compiling_makefiles.md
  - The Linux Kernel: the_linux_kernel.md
  - Loadable Kernel Modules: loadable_kernel_modules.md
  - About: about.md
  - ToDo: todo.md
theme: readthedocs
markdown_extensions:
    - smarty
    - admonition
    - mdx_figures
extra_css:
    - css/extra.css